web:
  image: binocarlos/moby-counter
  hostname: hello.weave.local
  net: demonet
  dns: 10.23.11.10
  environment:
     - "USE_REDIS_HOST=redis.weave.local"
redis:
  image: redis
  hostname: redis.weave.local
  net: demonet
  dns: 10.23.11.10
  environment:
     - "affinity:container==app_web_*"
  volume_driver: flocker
  volumes:
     - 'demo:/data'
