web:
  image: binocarlos/moby-counter
  hostname: hello.weave.local
  net: demonet
  environment:
     - "affinity:container!=app_web_*"
     - "USE_REDIS_HOST=redis.weave.local"
redis:
  image: redis
  hostname: redis.weave.local
  net: demonet
  volume_driver: flocker
  volumes:
     - 'demo:/data'
