web:
  image: binocarlos/moby-counter
  hostname: hello.weave.local
  publish_service: hello.demonet.weave
  dns: 10.23.11.10
  environment:
     - "USE_REDIS_HOST=redis.weave.local"
redis:
  image: redis
  hostname: redis.weave.local
  publish_service: redis.demonet.weave
  dns: 10.23.11.10
  environment:
     - "constraint:node==runner"
  volume_driver: flocker
  volumes:
     - 'demo:/data'
