web:
  build: .
  command: python hello.py
  ports:
     - "5000:5000"
  #volumes:
  #   - .:/code
  hostname: hello.weave.local
  net: 'weave:demo'
  dns: 10.1.42.1
redis:
  image: redis
  hostname: redis.weave.local
  net: 'weave:demo'
  dns: 10.1.42.1
